version: '3'

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    depends_on:
      - app
    ports:
      - "8080:80"

  app:
    build:
      context: node
    entrypoint: dockerize --wait tcp://db:3306 -timeout 20s node .
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    command: sh -c "npm install"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge